---
version: 0.2
phases:
  pre_build:
    commands:
      # install docker
      - sudo apt-get update
      - sudo apt install apt-transport-https ca-certificates curl
        software-properties-common
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg
        --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      - echo "deb [arch=$(dpkg --print-architecture)
        signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
        https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" |
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - sudo apt update
      - apt-cache policy docker-ce
      - sudo apt --assume-yes install docker-ce
      - sudo service docker restart
      # connect to repository:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c7l4l0y6
  build:
    commands:
      - docker build -t shira-hello-world .
  post_build:
    commands:
      - docker tag shira-hello-world:latest public.ecr.aws/c7l4l0y6/shira-hello-world:latest  
      - docker push public.ecr.aws/c7l4l0y6/shira-hello-world:latest
      # create imagedefinitions.json for deployment: 
      - echo '[{"name":"shirahw","imageUri":"public.ecr.aws/c7l4l0y6/shira-hello-world:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
