version: 0.2
phases:
  pre_build:
    commands:
      - aws --version
      - $(aws ecr get-login --region us-east-2 --no-include-email)
      - REPOSITORY_URI=public.ecr.aws/c7l4l0y6/shira-hello-world
  build:
    commands:
      - docker build -t public.ecr.aws/c7l4l0y6/shira-hello-world:latest .
  post_build:
    commands:
      - docker push public.ecr.aws/c7l4l0y6/shira-hello-world:latest
artifacts:
  files:
    - '**/*'
