version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-2
      -  sudo apt-get update
      -  sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      -  sudo service docker start
  build:
    commands:
      - docker build -t public.ecr.aws/c7l4l0y6/shira-hello-world:latest .
  post_build:
    commands:
      - docker push public.ecr.aws/c7l4l0y6/shira-hello-world:latest
artifacts:
  files:
    - '**/*'
